# Generated by Django 3.0.4 on 2020-03-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
                ('number', models.IntegerField()),
                ('neighborhood', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('federated_state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=8)),
            ],
        ),
    ]
